server:
  port: 9010
  servlet:
    encoding:
      charset: UTF-8
  compression:
    enabled: true
    min-response-size: 256
    mime-types:
      - text/html
      - text/xml
      - text/plain
      - text/css
      - text/javascript
      - application/javascript
      - application/json
  forward-headers-strategy: framework

spring:
  application:
    name: schedule-management
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  h2:
    console:
      enabled: true
  mvc:
    async:
      request-timeout: 60s
    converters:
      preferred-json-mapper: gson
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc.time_zone: UTC
        connection.isolation: READ_COMMITED
        enable_lazy_load_no_trans: true
        format_sql: true
        generate_statistics: true
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        globally_quoted_identifiers: true
    open-in-view: false
    show-sql: false

  datasource:
    tomcat:
      default-transaction-isolation: 2
      test-on-borrow: true
      validation-query: SELECT 1
      initial-size: 1
      min-idle: 1
      max-idle: 5
      max-active: 60
      max-age: 30000
      max-wait: 10000