spring:
  datasource:
    url: jdbc:postgresql://localhost:54320/schedule
    username: inna
    password: password

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        format_sql: true
